server:
  port: 252
  
spring:
   application:
    name: server-zuul
    
zuul: 
  #忽略 所有的  
  ignored-services: "*" 
  #设置统一前缀
  prefix: /cloud
  #路由
  routes: 
    mydept:
      serviceId: SERVER-USER
      path: /dept/**
    myfeign:
      serviceId: FEIGN-RIBBON-80
      path: /feign/**
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://nico.com:8000/eureka/,http://nico25.com:8001/eureka/,http://nico252.com:8002/eureka/
  instance:
    instance-id: server-zuul-252  #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址
      
info: 
  app.name: nico-server-zuul
  company.name: nico.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  